name: Automated JavaScript tests
on: [pull_request]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Node dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Test with jest
        run: yarn test
  Code-Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Node 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Node dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run coverage
        run: yarn coverage
      - name: Check if badge updated
        id: check_badge
        run: >
          if git diff --quiet .badges/coverage/js.svg; then
            echo "::set-output name=updated::0"
          else
            echo "::set-output name=updated::1"
          fi
        shell: bash
      - name: Commit coverage badge
        if: steps.check_badge.outputs.updated == 1
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .badges/coverage/js.svg
          git commit -m "Updated JavaScript coverage badge"
      - name: Push coverage badge
        if: steps.check_badge.outputs.updated == 1
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
