name: Automated Python tests
on: [pull_request]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Python dependencies
      run: |
        pip install -r python/requirements/install.txt
        pip install -r python/requirements/test.txt
    - name: Install Python project
      run: pip install -e python
    - name: Test with pytest
      run: >
        pytest
        --junitxml=artifacts/python/junit.xml --cov-report=
  Code-Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Python dependencies
      run: |
        pip install -r python/requirements/install.txt
        pip install -r python/requirements/test.txt
    - name: Install Python project
      run: pip install -e python
    - name: Run coverage
      run: |
        pip install -r python/requirements/test.txt
        pip install coverage-badge
        pytest --cov-report=term
    - name: Coverage badge
      run: |
        mkdir -p .badges/coverage
        rm -f .badges/coverage/python.svg
        coverage-badge -o .badges/coverage/python.svg
    - name: Check if badge updated
      id: check_badge
      run: >
        if git diff --quiet .badges/coverage/python.svg; then
          echo "::set-output name=updated::0"
        else
          echo "::set-output name=updated::1"
        fi
      shell: bash
    - name: Commit coverage badge
      if: steps.check_badge.outputs.updated == 1
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .badges/coverage/python.svg
        git commit -m "Updated Python coverage badge"
    - name: Push coverage badge
      if: steps.check_badge.outputs.updated == 1
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
